export const INITIALIZE_PARTS_LOADING = "INITIALIZE_PARTS_LOADING";
export const INITIALIZE_PARTS_SUCCESS = "INITIALIZE_PARTS_SUCCESS";
export const INITIALIZE_PARTS_ERROR = "INITIALIZE_PARTS_ERROR";
export const LOAD_SELECTIONS_FROM_LOCAL_STORAGE = "LOAD_SELECTIONS_FROM_LOCAL_STORAGE";
export const SELECT_PART = "SELECT_PART";
export const SET_EXPRESS_SERVICE = "SET_EXPRESS_SERVICE";
export const SET_CHIPSET_PREFERENCE = "SET_CHIPSET_PREFERENCE";
export const SET_GPU_BRAND_PREFERENCE = "SET_GPU_BRAND_PREFERENCE";
export const SET_CROSSFIRE_SLI_COMPATIBILITY_PREFERENCE = "SET_CROSSFIRE_SLI_COMPATIBILITY_PREFERENCE";
export const RESET_PARTS_STATE = "RESET_PARTS_STATE";

export const AUTHENTICATE_LOADING = "AUTHENTICATE_LOADING";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_ERROR = "AUTHENTICATE_ERROR";
export const SET_AUTH_ERROR_MESSAGE = "SET_AUTH_ERROR_MESSAGE";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_ERROR = "UPDATE_USER_DETAILS_ERROR";
export const UPDATE_TOKEN_AFTER_PASSWORD_CHANGE = "UPDATE_TOKEN_AFTER_PASSWORD_CHANGE";
export const LOGOUT = "LOGOUT";

export const ENABLE_CANCEL_SELECTED_ORDER = "ENABLE_CANCEL_SELECTED_ORDER";
export const DISABLE_CANCEL_SELECTED_ORDER = "DISABLE_CANCEL_SELECTED_ORDER";
export const SET_CANCELLING_STATE = "SET_CANCELLING_STATE";
export const SET_CHECKOUT_LOADING_STATE = "SET_CHECKOUT_LOADING_STATE";